# 需要监控的项目
display:
  - all
  - overview
  - gc
  - thread
  - thread_used
  - thread_state
  - thread_info
  - heap_memory
  - jdk_thread_pool
  - dubbo_thread_pool
  - tomcat_thread_pool
  - mq_thread_pool
# 端口号
port: 12346
# 应用名称
applicationName: metrics